apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  namespace: detox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
        - name: webserver
          image: detox/webserver:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
            - containerPort: 9090
          envFrom:
            - configMapRef:
                name: detox-config
          env:
            - name: SPRING_R2DBC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: detox-secret
                  key: SPRING_R2DBC_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: webserver
  namespace: detox
spec:
  selector:
    app: webserver
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: grpc
      port: 9090
      targetPort: 9090
