# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import ai_agent_review_pb2 as ai__agent__review__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ai_agent_review_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AiAgentReviewServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamReview = channel.unary_stream(
                '/ai.agent.v1.AiAgentReviewService/StreamReview',
                request_serializer=ai__agent__review__pb2.ReviewRequest.SerializeToString,
                response_deserializer=ai__agent__review__pb2.ReviewToken.FromString,
                _registered_method=True)
        self.AnalyzeUsage = channel.unary_unary(
                '/ai.agent.v1.AiAgentReviewService/AnalyzeUsage',
                request_serializer=ai__agent__review__pb2.ReviewRequest.SerializeToString,
                response_deserializer=ai__agent__review__pb2.AnalysisResponse.FromString,
                _registered_method=True)


class AiAgentReviewServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamReview(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeUsage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AiAgentReviewServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamReview': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamReview,
                    request_deserializer=ai__agent__review__pb2.ReviewRequest.FromString,
                    response_serializer=ai__agent__review__pb2.ReviewToken.SerializeToString,
            ),
            'AnalyzeUsage': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeUsage,
                    request_deserializer=ai__agent__review__pb2.ReviewRequest.FromString,
                    response_serializer=ai__agent__review__pb2.AnalysisResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai.agent.v1.AiAgentReviewService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai.agent.v1.AiAgentReviewService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AiAgentReviewService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamReview(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ai.agent.v1.AiAgentReviewService/StreamReview',
            ai__agent__review__pb2.ReviewRequest.SerializeToString,
            ai__agent__review__pb2.ReviewToken.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnalyzeUsage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.agent.v1.AiAgentReviewService/AnalyzeUsage',
            ai__agent__review__pb2.ReviewRequest.SerializeToString,
            ai__agent__review__pb2.AnalysisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
