# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai_agent_review.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ai_agent_review.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x61i_agent_review.proto\x12\x0b\x61i.agent.v1\"\x99\x01\n\x0b\x44omainUsage\x12\x0e\n\x06\x64omain\x18\x01 \x01(\t\x12\x15\n\rrequest_count\x18\x02 \x01(\x03\x12\x14\n\x0c\x66irst_access\x18\x03 \x01(\x03\x12\x13\n\x0blast_access\x18\x04 \x01(\x03\x12\x16\n\x0etotal_duration\x18\x05 \x01(\x03\x12 \n\x18\x61verage_response_time_ms\x18\x06 \x01(\x03\"\x89\x01\n\x08UsageDto\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0e\n\x06period\x18\x02 \x01(\t\x12\x15\n\rtotal_queries\x18\x03 \x01(\x03\x12\x16\n\x0eunique_domains\x18\x04 \x01(\x03\x12-\n\x0btop_domains\x18\x05 \x03(\x0b\x32\x18.ai.agent.v1.DomainUsage\"Y\n\rReviewRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x0e\n\x06prompt\x18\x02 \x01(\t\x12$\n\x05usage\x18\x03 \x01(\x0b\x32\x15.ai.agent.v1.UsageDto\"M\n\x0bReviewToken\x12\r\n\x05token\x18\x01 \x01(\t\x12\x0c\n\x04\x64one\x18\x02 \x01(\x08\x12\r\n\x05model\x18\x03 \x01(\t\x12\x12\n\nmessage_id\x18\x04 \x01(\t\"[\n\x16\x42lockingRecommendation\x12\x0e\n\x06\x64omain\x18\x01 \x01(\t\x12\x0e\n\x06reason\x18\x02 \x01(\t\x12!\n\x19recommended_limit_minutes\x18\x03 \x01(\x03\"\xc6\x01\n\x10\x41nalysisResponse\x12\x13\n\x0bis_addicted\x18\x01 \x01(\x08\x12\x12\n\nrisk_level\x18\x02 \x01(\t\x12\x0f\n\x07summary\x18\x03 \x01(\t\x12\x16\n\x0erecommendation\x18\x04 \x01(\t\x12\x19\n\x11\x61\x64\x64ictive_domains\x18\x05 \x03(\t\x12\x45\n\x18\x62locking_recommendations\x18\x06 \x03(\x0b\x32#.ai.agent.v1.BlockingRecommendation2\xa9\x01\n\x14\x41iAgentReviewService\x12\x46\n\x0cStreamReview\x12\x1a.ai.agent.v1.ReviewRequest\x1a\x18.ai.agent.v1.ReviewToken0\x01\x12I\n\x0c\x41nalyzeUsage\x12\x1a.ai.agent.v1.ReviewRequest\x1a\x1d.ai.agent.v1.AnalysisResponseB:\n\"com.pnu.detox_agent.webserver.grpcB\x12\x41iAgentReviewProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai_agent_review_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\"com.pnu.detox_agent.webserver.grpcB\022AiAgentReviewProtoP\001'
  _globals['_DOMAINUSAGE']._serialized_start=39
  _globals['_DOMAINUSAGE']._serialized_end=192
  _globals['_USAGEDTO']._serialized_start=195
  _globals['_USAGEDTO']._serialized_end=332
  _globals['_REVIEWREQUEST']._serialized_start=334
  _globals['_REVIEWREQUEST']._serialized_end=423
  _globals['_REVIEWTOKEN']._serialized_start=425
  _globals['_REVIEWTOKEN']._serialized_end=502
  _globals['_BLOCKINGRECOMMENDATION']._serialized_start=504
  _globals['_BLOCKINGRECOMMENDATION']._serialized_end=595
  _globals['_ANALYSISRESPONSE']._serialized_start=598
  _globals['_ANALYSISRESPONSE']._serialized_end=796
  _globals['_AIAGENTREVIEWSERVICE']._serialized_start=799
  _globals['_AIAGENTREVIEWSERVICE']._serialized_end=968
# @@protoc_insertion_point(module_scope)
