# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: usage.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'usage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0busage.proto\x12\x05usage\"N\n\x0b\x44omainUsage\x12\x0e\n\x06\x64omain\x18\x01 \x01(\t\x12\x18\n\x10\x64uration_seconds\x18\x02 \x01(\x03\x12\x15\n\rlast_accessed\x18\x03 \x01(\t\"\x1e\n\x0cUsageRequest\x12\x0e\n\x06period\x18\x01 \x01(\t\"7\n\rUsageResponse\x12&\n\nusage_list\x18\x01 \x03(\x0b\x32\x12.usage.DomainUsage2E\n\x0cUsageService\x12\x35\n\x08GetUsage\x12\x13.usage.UsageRequest\x1a\x14.usage.UsageResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'usage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DOMAINUSAGE']._serialized_start=22
  _globals['_DOMAINUSAGE']._serialized_end=100
  _globals['_USAGEREQUEST']._serialized_start=102
  _globals['_USAGEREQUEST']._serialized_end=132
  _globals['_USAGERESPONSE']._serialized_start=134
  _globals['_USAGERESPONSE']._serialized_end=189
  _globals['_USAGESERVICE']._serialized_start=191
  _globals['_USAGESERVICE']._serialized_end=260
# @@protoc_insertion_point(module_scope)
